name: build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      packages: write
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: docker build
        run: docker build -t ghcr.io/khorwood/certbot .
      - name: docker push
        run: docker push ghcr.io/khorwood/certbot:latest
