name: build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
      - name: docker build
        run: docker build -t ghcr.io/khorwood/certbot .
      - name: docker push
        run: docker push ghcr.io/khorwood/certbot:latest
