name: pull-request
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: uses actions/checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
      - name: uses hadolint/hadolint-action
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf #v3.1.0
        with:
          dockerfile: Dockerfile
